### PR TITLE
Added b2.cancelLargeFile() function

### PR DESCRIPTION
**Pull request by c-reiter**
I saw the package didn't support the b2_cancel_large_file Endpoint, so I added the missing function to index.js
More Info on cancel_large_file here: https://www.backblaze.com/b2/docs/b2_cancel_large_file.html

I hope my process of submitting this is right, as this is my first public pull request and I couldn't find contribution guidelines for this repo. Thanks for all your work on the package, it really helped me!

### CODE REVIEW

**Comment by Cherry** [comment]
Thanks for the PR @c-reiter! It appears there are a few minor ESLint style errors that are causing the tests to fail - can you please take a look at these and we'll get this merged soon? 😃

**Comment by c-reiter** [comment]
Yes, of course, I'll take a look and update you as soon as I get the style errors fixed!

**Comment by c-reiter** [comment]
@Cherry fixed the errors, added tests, everything worked and passed :)

**Comment by Cherry** [comment]
Thanks very much @c-reiter. I'll merge this today and draft a new release next week. Have a great weekend!

**Comment by c-reiter** [comment]
You're welcome! Have a nice weekend too!

**Pull request merged**
